In [1]:
import numpy as np
import pandas as pd
from collections import Counter 
import matplotlib.pyplot as plt
import math

In [2]:
data_business=pd.read_csv('Business.csv',index_col=0)

In [3]:
category_frequency = []
num_tags = []

for i in range(data_business.shape[0]):
    each_line = data_business['category'][i].split(", ")
    for content in each_line:
        category_frequency.append(content)
        num_tags.append(len(content))

In [4]:
sum(num_tags) / len(num_tags)

10.020931278361473

In [5]:
data_business.business_id.describe()

count                      23509
unique                     23509
top       LXt2Aycp2ILMWQmKsjl4Wg
freq                           1
Name: business_id, dtype: object

In [6]:
new_feature = Counter(category_frequency).most_common(63)

feature = pd.DataFrame()
for ind,val in enumerate(new_feature[2:]):
    feature.loc[ind,'Feature'] = val[0]
    feature.loc[ind,'IDF'] =  math.log1p(len(data_business.business_id) / val[1])

In [7]:
data_business2 = data_business

In [8]:
for tag in range(feature.shape[0]):
    ft = feature.loc[tag,'Feature']
    for i in range(data_business2.shape[0]):
        each_line = data_business2['category'][i].split(", ")
        if ft in each_line:
            data_business2.loc[i,ft] = 1 
        else:
            data_business2.loc[i,ft] = 0

In [15]:
data_business2.describe()
data_business2.to_csv('Business2.csv')

In [16]:
data_business2.head()

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,...,Vietnamese,Food Delivery Services,Automotive,Greek,Food Trucks,Health Markets,Wine Bars,Gluten-Free,Buffets,French
0,1Dfx3zM-rW4n-31KeC8sJg,Taco Bell,2450 E Indian School Rd,Phoenix,AZ,85016,33.495194,-112.028588,3.0,18,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,PZ-LZzSlhSe9utkQYU8pFg,Carluccio's Tivoli Gardens,"1775 E Tropicana Ave, Ste 29",Las Vegas,NV,89119,36.100016,-115.128528,4.0,40,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,tstimHoMcYbkSC4eBA1wEg,Maria's Mexican Restaurant & Bakery,6055 E Lake Mead Blvd,Las Vegas,NV,89156,36.195615,-115.040529,4.5,184,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,C9oCPomVP0mtKa8z99E3gg,Bakery Gateau,"865 York Mills Road, Unit 1",Toronto,ON,M3B 1Y6,43.754093,-79.349548,4.5,8,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,NDuUMJfrWk52RA-H-OtrpA,Bolt Fresh Bar,1170 Queen Street W,Toronto,ON,M6J 1J5,43.642889,-79.425429,3.0,57,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [17]:
new_feature = Counter(category_frequency).most_common(1000)
newdt = pd.DataFrame(new_feature)
newdt.describe()

                  1
count    720.000000
mean     135.894444
std      834.151129
min        1.000000
25%        1.000000
50%        4.000000
75%       34.000000
max    18413.000000

In [18]:
new_feature

[('Restaurants', 18413),
 ('Food', 9987),
 ('Nightlife', 2737),
 ('Coffee & Tea', 2675),
 ('Bars', 2573),
 ('Fast Food', 2201),
 ('Sandwiches', 2056),
 ('Mexican', 1860),
 ('American (Traditional)', 1819),
 ('Pizza', 1704),
 ('Breakfast & Brunch', 1703),
 ('Specialty Food', 1642),
 ('Burgers', 1516),
 ('Italian', 1379),
 ('Chinese', 1361),
 ('American (New)', 1356),
 ('Desserts', 1239),
 ('Bakeries', 1189),
 ('Cafes', 1119),
 ('Grocery', 1063),
 ('Japanese', 1045),
 ('Event Planning & Services', 1036),
 ('Shopping', 967),
 ('Ice Cream & Frozen Yogurt', 862),
 ('Seafood', 825),
 ('Sushi Bars', 774),
 ('Asian Fusion', 730),
 ('Juice Bars & Smoothies', 721),
 ('Chicken Wings', 709),
 ('Convenience Stores', 700),
 ('Salad', 695),
 ('Canadian (New)', 694),
 ('Beer', 690),
 ('Wine & Spirits', 690),
 ('Caterers', 655),
 ('Mediterranean', 599),
 ('Barbeque', 580),
 ('Arts & Entertainment', 521),
 ('Thai', 514),
 ('Delis', 512),
 ('Sports Bars', 489),
 ('Pubs', 480),
 ('Indian', 451),
 ('Middle Eastern', 444),
 ('Korean', 432),
 ('Vegetarian', 421),
 ('Steakhouses', 420),
 ('Diners', 385),
 ('Vegan', 381),
 ('Gas Stations', 370),
 ('Cocktail Bars', 367),
 ('Ethnic Food', 366),
 ('Lounges', 364),
 ('Vietnamese', 357),
 ('Food Delivery Services', 356),
 ('Automotive', 348),
 ('Greek', 327),
 ('Food Trucks', 321),
 ('Health Markets', 303),
 ('Wine Bars', 297),
 ('Gluten-Free', 295),
 ('Buffets', 286),
 ('French', 284),
 ('Comfort Food', 278),
 ('Drugstores', 243),
 ('Hot Dogs', 237),
 ('Soup', 235),
 ('Caribbean', 224),
 ('Donuts', 223),
 ('Latin American', 217),
 ('Local Flavor', 209),
 ('Gastropubs', 205),
 ('Halal', 204),
 ('Tex-Mex', 203),
 ('Hotels & Travel', 203),
 ('Bubble Tea', 198),
 ('Tapas/Small Plates', 193),
 ('Hawaiian', 193),
 ('Tea Rooms', 189),
 ('Noodles', 187),
 ('Beauty & Spas', 180),
 ('Venues & Event Spaces', 177),
 ('Chicken Shop', 177),
 ('Food Stands', 168),
 ('Bagels', 164),
 ('Chocolatiers & Shops', 156),
 ('Street Vendors', 156),
 ('Tapas Bars', 154),
 ('Southern', 153),
 ('Meat Shops', 141),
 ('Fashion', 141),
 ('Pakistani', 139),
 ('Casinos', 139),
 ('Health & Medical', 138),
 ('Music Venues', 138),
 ('Hotels', 135),
 ('Filipino', 132),
 ('Cosmetics & Beauty Supply', 128),
 ('Active Life', 126),
 ('Farmers Market', 125),
 ('Tacos', 121),
 ('Imported Food', 120),
 ('Breweries', 117),
 ('Flowers & Gifts', 117),
 ('Candy Stores', 113),
 ('Dim Sum', 111),
 ('Ramen', 111),
 ('Local Services', 110),
 ('Shaved Ice', 108),
 ('Beer Bar', 107),
 ('Department Stores', 102),
 ('Fruits & Veggies', 102),
 ('Food Court', 102),
 ('Soul Food', 101),
 ('Cajun/Creole', 100),
 ('Fish & Chips', 97),
 ('Karaoke', 97),
 ('Photography Stores & Services', 95),
 ('Cupcakes', 88),
 ('Vitamins & Supplements', 86),
 ('Party & Event Planning', 86),
 ('Organic Stores', 86),
 ('Custom Cakes', 85),
 ('Do-It-Yourself Food', 84),
 ('Dance Clubs', 81),
 ('Dive Bars', 80),
 ('Portuguese', 78),
 ('Persian/Iranian', 75),
 ('Modern European', 74),
 ('Seafood Markets', 74),
 ('Spanish', 74),
 ('Creperies', 73),
 ('Taiwanese', 73),
 ('Poke', 71),
 ('Discount Store', 71),
 ('Kosher', 65),
 ('Butcher', 64),
 ('Internet Cafes', 64),
 ('Cheese Shops', 64),
 ('Home & Garden', 64),
 ('Cheesesteaks', 63),
 ('Nutritionists', 62),
 ('British', 62),
 ('Coffee Roasteries', 59),
 ('African', 57),
 ('Professional Services', 57),
 ('Home Services', 57),
 ('Florists', 57),
 ('Patisserie/Cake Shop', 56),
 ('Irish', 56),
 ('Gelato', 55),
 ('Gift Shops', 55),
 ('Ethiopian', 54),
 ('Car Wash', 53),
 ('Hookah Bars', 52),
 ('Festivals', 52),
 ('International Grocery', 51),
 ('Cantonese', 49),
 ('Hot Pot', 48),
 ('Poutineries', 47),
 ('Falafel', 47),
 ('Waffles', 46),
 ('Afghan', 46),
 ('Turkish', 45),
 ('Education', 43),
 ('Tobacco Shops', 42),
 ('Arcades', 42),
 ('Lebanese', 41),
 ('Service Stations', 41),
 ('Herbs & Spices', 40),
 ('Wholesale Stores', 40),
 ('Electronics', 40),
 ('Salvadoran', 39),
 ('Cuban', 39),
 ('Tours', 39),
 ('Shopping Centers', 36),
 ('Peruvian', 35),
 ('Brazilian', 35),
 ('Szechuan', 35),
 ('Delicatessen', 34),
 ('Personal Chefs', 34),
 ('Wraps', 34),
 ('Pretzels', 33),
 ('Art Galleries', 33),
 ('Polish', 32),
 ('Books', 32),
 ('Mags', 32),
 ('Music & Video', 32),
 ('Himalayan/Nepalese', 32),
 ('Macarons', 31),
 ('Performing Arts', 30),
 ('Acai Bowls', 30),
 ('Arts & Crafts', 30),
 ('Jazz & Blues', 29),
 ('Party Supplies', 29),
 ('Live/Raw Food', 29),
 ('Malaysian', 27),
 ('Russian', 27),
 ('German', 27),
 ('Pool Halls', 27),
 ('Bistros', 26),
 ('Wineries', 25),
 ('Pets', 25),
 ('Wedding Planning', 25),
 ('Mobile Phones', 25),
 ('Pharmacy', 25),
 ('Brasseries', 25),
 ('New Mexican Cuisine', 24),
 ('Kebab', 24),
 ('Water Stores', 23),
 ('Day Spas', 23),
 ('Kitchen & Bath', 23),
 ('Adult Entertainment', 23),
 ('Specialty Schools', 23),
 ('Weight Loss Centers', 22),
 ('Resorts', 21),
 ('Irish Pub', 21),
 ('Moroccan', 21),
 ('Fitness & Instruction', 21),
 ('Home Decor', 21),
 ('Argentine', 20),
 ('Pan Asian', 19),
 ('Social Clubs', 19),
 ('Food Tours', 19),
 ('Community Service/Non-Profit', 18),
 ('Wholesalers', 18),
 ('Pasta Shops', 18),
 ('Hobby Shops', 18),
 ('Amusement Parks', 18),
 ('Smokehouse', 17),
 ('Furniture Stores', 17),
 ('Golf', 17),
 ('Arabian', 17),
 ('Toy Stores', 17),
 ('Brewpubs', 16),
 ("Women's Clothing", 16),
 ('Coffee & Tea Supplies', 16),
 ('Popcorn Shops', 15),
 ('Personal Shopping', 15),
 ('Pet Stores', 15),
 ('Skin Care', 15),
 ('Belgian', 15),
 ('Appliances', 15),
 ('Hair Salons', 15),
 ('Water Delivery', 14),
 ('Water Purification Services', 14),
 ('Izakaya', 14),
 ('Gay Bars', 14),
 ('Jewelry', 14),
 ('Coffeeshops', 14),
 ('Pet Services', 14),
 ('International', 14),
 ('Mongolian', 13),
 ('Sporting Goods', 13),
 ('Doctors', 13),
 ('Vape Shops', 13),
 ('Sri Lankan', 13),
 ('Venezuelan', 13),
 ('Ukrainian', 12),
 ('Ethnic Grocery', 12),
 ('Head Shops', 12),
 ('Swimming Pools', 12),
 ('Cooking Schools', 12),
 ('Singaporean', 12),
 ('Couriers & Delivery Services', 12),
 ("Men's Clothing", 12),
 ('Bookstores', 12),
 ('Souvenir Shops', 11),
 ('Public Services & Government', 11),
 ('Public Markets', 11),
 ('Cafeteria', 11),
 ('Party Equipment Rentals', 11),
 ('Donairs', 11),
 ('Teppanyaki', 11),
 ('Cooking Classes', 11),
 ('Real Estate', 11),
 ('Hungarian', 10),
 ('Bangladeshi', 10),
 ('Accessories', 10),
 ('Colombian', 10),
 ('Comedy Clubs', 10),
 ('Wigs', 10),
 ('Hakka', 10),
 ('Fondue', 10),
 ('Indonesian', 10),
 ('Cards & Stationery', 10),
 ('Beverage Store', 10),
 ('Whiskey Bars', 9),
 ('Ethical Grocery', 9),
 ('Cinema', 9),
 ('Trainers', 9),
 ('Massage', 9),
 ('Contractors', 9),
 ('Plumbing', 9),
 ('Hair Removal', 9),
 ('Laotian', 9),
 ('Bowling', 9),
 ('Shaved Snow', 9),
 ('Videos & Video Game Rental', 9),
 ('South African', 9),
 ('Dinner Theater', 9),
 ('Beer Gardens', 8),
 ('Gyms', 8),
 ('Art Classes', 8),
 ('Religious Organizations', 8),
 ('Walking Tours', 8),
 ('Financial Services', 8),
 ('Tabletop Games', 8),
 ('Naturopathic/Holistic', 8),
 ('Antiques', 8),
 ('Piano Bars', 8),
 ('Recreation Centers', 7),
 ('Nail Salons', 7),
 ('Shanghainese', 7),
 ('Outlet Stores', 7),
 ('Puerto Rican', 7),
 ('CSA', 6),
 ('Stadiums & Arenas', 6),
 ('Yoga', 6),
 ('Medical Centers', 6),
 ('Laundry Services', 6),
 ('Transportation', 6),
 ('Kids Activities', 6),
 ('Playgrounds', 6),
 ('Oil Change Stations', 6),
 ('Nurseries & Gardening', 6),
 ('Dry Cleaning & Laundry', 6),
 ('Restaurant Supplies', 6),
 ('Appliances & Repair', 6),
 ('Basque', 6),
 ('Auto Repair', 6),
 ('LAN Centers', 6),
 ('Parks', 5),
 ('Sports Clubs', 5),
 ('Ice Delivery', 5),
 ('Conveyor Belt Sushi', 5),
 ('Pop-up Shops', 5),
 ('Bikes', 5),
 ('Special Education', 5),
 ('Vinyl Records', 5),
 ('Museums', 5),
 ('Medical Spas', 5),
 ('Pet Sitting', 5),
 ('Alternative Medicine', 5),
 ('IT Services & Computer Repair', 5),
 ('Pop-Up Restaurants', 5),
 ('Hospitals', 5),
 ('Scandinavian', 5),
 ('Japanese Curry', 5),
 ('Marketing', 5),
 ('Massage Therapy', 5),
 ('Themed Cafes', 5),
 ('Musicians', 5),
 ('Sports Wear', 5),
 ('Business Consulting', 5),
 ('Airports', 5),
 ('Beer Tours', 5),
 ('Distilleries', 5),
 ('Food Banks', 4),
 ('Bed & Breakfast', 4),
 ('Cannabis Dispensaries', 4),
 ('Tanning', 4),
 ('Hong Kong Style Cafe', 4),
 ('Home Cleaning', 4),
 ('Grilling Equipment', 4),
 ('Outdoor Furniture Stores', 4),
 ('Travel Services', 4),
 ('Limos', 4),
 ('Churches', 4),
 ('Dog Walkers', 4),
 ('Wine Tours', 4),
 ('Office Equipment', 4),
 ('Egyptian', 4),
 ('Herbal Shops', 4),
 ('Acupuncture', 4),
 ('Music & DVDs', 4),
 ('Australian', 4),
 ('Country Clubs', 4),
 ('Olive Oil', 4),
 ('Real Estate Services', 4),
 ('Cambodian', 4),
 ('Fireplace Services', 4),
 ('Cultural Center', 4),
 ('Auto Glass Services', 4),
 ('Propane', 4),
 ('Wine Tasting Room', 3),
 ('Honduran', 3),
 ('Farms', 3),
 ('Landmarks & Historical Buildings', 3),
 ('Tires', 3),
 ('Party Bus Rentals', 3),
 ('Tuscan', 3),
 ('Thrift Stores', 3),
 ('Paint & Sip', 3),
 ('Bike Repair/Maintenance', 3),
 ('Empanadas', 3),
 ('Lawyers', 3),
 ('Waxing', 3),
 ('Eyelash Service', 3),
 ('Auto Detailing', 3),
 ('Laser Hair Removal', 3),
 ('Czech', 3),
 ('Meditation Centers', 3),
 ('Newspapers & Magazines', 3),
 ('Spray Tanning', 3),
 ('Saunas', 3),
 ('Tennis', 3),
 ('Masonry/Concrete', 3),
 ('Cannabis Clinics', 3),
 ('Internet Service Providers', 3),
 ('Art Schools', 3),
 ('Video Game Stores', 3),
 ('Champagne Bars', 3),
 ('Strip Clubs', 3),
 ('Flea Markets', 3),
 ('Printing Services', 3),
 ('Used', 3),
 ('Vintage & Consignment', 3),
 ('Real Estate Agents', 3),
 ('Tiki Bars', 3),
 ('Cabaret', 3),
 ('DJs', 3),
 ('Rehabilitation Center', 3),
 ('Pub Food', 3),
 ('Smog Check Stations', 3),
 ('Armenian', 3),
 ('Car Window Tinting', 3),
 ('Speakeasies', 3),
 ('Veterinarians', 3),
 ('Adult Education', 3),
 ('Historical Tours', 3),
 ('Bartenders', 3),
 ('Honey', 3),
 ('Heating & Air Conditioning/HVAC', 3),
 ('Shared Office Spaces', 3),
 ('Educational Services', 3),
 ('Nicaraguan', 2),
 ('Beach Bars', 2),
 ('Horse Racing', 2),
 ('Air Duct Cleaning', 2),
 ('Dentists', 2),
 ('Cideries', 2),
 ('Personal Assistants', 2),
 ('Dry Cleaning', 2),
 ('Scottish', 2),
 ('Zoos', 2),
 ('Outdoor Gear', 2),
 ('Country Dance Halls', 2),
 ('Nail Technicians', 2),
 ('Uzbek', 2),
 ('Bounce House Rentals', 2),
 ('Barbers', 2),
 ('Indoor Playcentre', 2),
 ('Team Building Activities', 2),
 ('Syrian', 2),
 ('Home Health Care', 2),
 ('Skating Rinks', 2),
 ('Landscaping', 2),
 ('Bankruptcy Law', 2),
 ('Investing', 2),
 ('Austrian', 2),
 ('Brewing Supplies', 2),
 ('Slovakian', 2),
 ('Ticket Sales', 2),
 ('Eyewear & Opticians', 2),
 ('Makeup Artists', 2),
 ('Haitian', 2),
 ('Hair Extensions', 2),
 ('Colleges & Universities', 2),
 ('Baby Gear & Furniture', 2),
 ('Knitting Supplies', 2),
 ('Bike Rentals', 2),
 ('Pet Adoption', 2),
 ('Laundromat', 2),
 ('Tax Services', 2),
 ('Accountants', 2),
 ('Sewing & Alterations', 2),
 ('Shoe Stores', 2),
 ('Metal Fabricators', 2),
 ('Bridal', 2),
 ('Wedding Chapels', 2),
 ('Public Transportation', 2),
 ('Optometrists', 2),
 ('Interior Design', 2),
 ('Photo Booth Rentals', 2),
 ('Hair Stylists', 2),
 ('Screen Printing', 2),
 ('Dominican', 2),
 ('Community Centers', 2),
 ('Race Tracks', 2),
 ('Reflexology', 2),
 ('Life Coach', 2),
 ('Traditional Chinese Medicine', 2),
 ('Reiki', 2),
 ('Occupational Therapy', 2),
 ('Physical Therapy', 2),
 ('Supernatural Readings', 2),
 ('Community Gardens', 2),
 ('Windshield Installation & Repair', 2),
 ('Eatertainment', 2),
 ('Pool & Billiards', 2),
 ('Guamanian', 2),
 ('Burmese', 2),
 ('Iberian', 2),
 ('Trinidadian', 2),
 ('Golf Equipment', 2),
 ('Vehicle Wraps', 2),
 ('Trophy Shops', 2),
 ('Hats', 2),
 ('Photographers', 2),
 ('Handyman', 2),
 ('Kombucha', 2),
 ('Auto Parts & Supplies', 2),
 ('Body Shops', 2),
 ('Yelp Events', 2),
 ('Tasting Classes', 2),
 ('Web Design', 2),
 ('Martial Arts', 2),
 ('Pest Control', 2),
 ('Mailbox Centers', 1),
 ('Amateur Sports Teams', 1),
 ('Boot Camps', 1),
 ('Interval Training Gyms', 1),
 ('Street Art', 1),
 ('Fire Protection Services', 1),
 ('Office Cleaning', 1),
 ('Laboratory Testing', 1),
 ('Diagnostic Services', 1),
 ('Threading Services', 1),
 ('Cosmetic Dentists', 1),
 ('Airport Shuttles', 1),
 ('Security Services', 1),
 ('Car Rental', 1),
 ('Trampoline Parks', 1),
 ('Climbing', 1),
 ('Laser Tag', 1),
 ('Tableware', 1),
 ('Family Practice', 1),
 ('Mosques', 1),
 ('Acne Treatment', 1),
 ('Japanese Sweets', 1),
 ('General Dentistry', 1),
 ('Czech/Slovakian', 1),
 ('Notaries', 1),
 ('Movers', 1),
 ('Police Departments', 1),
 ('Watches', 1),
 ('Banks & Credit Unions', 1),
 ('Aquariums', 1),
 ('Aquarium Services', 1),
 ('Local Fish Stores', 1),
 ('Mobile Phone Repair', 1),
 ('Tanning Beds', 1),
 ('Comic Books', 1),
 ('Scavenger Hunts', 1),
 ('Swiss Food', 1),
 ('Pet Boarding', 1),
 ('Cardiologists', 1),
 ('Emergency Medicine', 1),
 ('Pediatricians', 1),
 ('Buddhist Temples', 1),
 ('Computers', 1),
 ('Tickets', 1),
 ('Leather Goods', 1),
 ("Children's Clothing", 1),
 ('Shipping Centers', 1),
 ('Tattoo', 1),
 ('Club Crawl', 1),
 ('Skydiving', 1),
 ('Beer Garden', 1),
 ('Apartments', 1),
 ('Animal Shelters', 1),
 ('Minho', 1),
 ('Motorcycle Dealers', 1),
 ('RV Parks', 1),
 ('Attraction Farms', 1),
 ('Pet Training', 1),
 ('Backshop', 1),
 ('Customized Merchandise', 1),
 ('Udon', 1),
 ('Medical Supplies', 1),
 ('Shoe Repair', 1),
 ('Passport & Visa Services', 1),
 ('Escape Games', 1),
 ('Train Stations', 1),
 ('Flooring', 1),
 ('Damage Restoration', 1),
 ('Roofing', 1),
 ('Home Inspectors', 1),
 ('Pilates', 1),
 ('Furniture Rental', 1),
 ('Fur Clothing', 1),
 ('Lighting Fixtures & Equipment', 1),
 ('Furniture Repair', 1),
 ('Audio/Visual Equipment Rental', 1),
 ('Security Systems', 1),
 ('Blow Dry/Out Services', 1),
 ('Electricians', 1),
 ('Mobile Phone Accessories', 1),
 ('Pick Your Own Farms', 1),
 ('Mass Media', 1),
 ('Radio Stations', 1),
 ('Gun/Rifle Ranges', 1),
 ('Go Karts', 1),
 ('Float Spa', 1),
 ('Health Coach', 1),
 ('Rolfing', 1),
 ('Firewood', 1),
 ('Oaxacan', 1),
 ('Speech Therapists', 1),
 ('Mortgage Brokers', 1),
 ('Hardware Stores', 1),
 ('Personal Care Services', 1),
 ('Psychics', 1),
 ('Health Retreats', 1),
 ('Livestock Feed & Supply', 1),
 ('Musical Instruments & Teachers', 1),
 ('Pet Groomers', 1),
 ('Auto Customization', 1),
 ('Signmaking', 1),
 ('Feng Shui', 1),
 ('Session Photography', 1),
 ('Midwives', 1),
 ('Placenta Encapsulations', 1),
 ('Childbirth Education', 1),
 ('Doulas', 1),
 ('Bus Tours', 1),
 ('Registration Services', 1),
 ('Departments of Motor Vehicles', 1),
 ('Outdoor Movies', 1),
 ('Studio Taping', 1),
 ('Paint-Your-Own Pottery', 1),
 ('Art Supplies', 1),
 ('Bocce Ball', 1),
 ('Beaches', 1),
 ('Car Dealers', 1),
 ('Professional Sports Teams', 1),
 ('Public Relations', 1),
 ('Knife Sharpening', 1),
 ('Courthouses', 1),
 ('Swimwear', 1),
 ('Surf Schools', 1),
 ('Awnings', 1),
 ('Fences & Gates', 1),
 ('Cabinetry', 1),
 ('Spiritual Shop', 1),
 ('Utilities', 1),
 ('Beer Hall', 1),
 ('Transmission Repair', 1),
 ('Auto Insurance', 1),
 ('Insurance', 1),
 ('Towing', 1),
 ('Archery', 1),
 ('Home Window Tinting', 1),
 ('Leisure Centers', 1),
 ('Art Museums', 1),
 ('Pool & Hot Tub Service', 1),
 ('Soba', 1),
 ('Fitness/Exercise Equipment', 1),
 ('Drive-Thru Bars', 1),
 ('Airport Lounges', 1),
 ('Bulgarian', 1),
 ('Pain Management', 1),
 ('Botanical Gardens', 1),
 ('Milkshake Bars', 1),
 ('Building Supplies', 1),
 ('Hainan', 1),
 ('Mattresses', 1),
 ('ATV Rentals/Tours', 1),
 ('Luggage', 1),
 ('Kitchen Incubators', 1),
 ('Bartending Schools', 1),
 ('Bingo Halls', 1),
 ('Airport Terminals', 1),
 ('Colonics', 1),
 ('Party Characters', 1),
 ('Commercial Truck Repair', 1),
 ('Truck Rental', 1),
 ('Divorce & Family Law', 1),
 ('Personal Injury Law', 1),
 ('Immigration Law', 1),
 ('Reunion', 1),
 ('Hydrotherapy', 1),
 ('Supper Clubs', 1),
 ('Aircraft Repairs', 1),
 ('Airsoft', 1),
 ('Balloon Services', 1),
 ('Graphic Design', 1),
 ('Screen Printing/T-Shirt Printing', 1),
 ('Advertising', 1),
 ('Wine Tasting Classes', 1),
 ('Drywall Installation & Repair', 1),
 ('Painters', 1),
 ('Brazilian Jiu-jitsu', 1),
 ('Traditional Clothing', 1),
 ('Gardeners', 1),
 ('Property Management', 1),
 ('Vocational & Technical School', 1),
 ('Barre Classes', 1),
 ('Self Storage', 1),
 ('Bar Crawl', 1),
 ('Engraving', 1),
 ('Cycling Classes', 1),
 ('Spin Classes', 1),
 ('Legal Services', 1),
 ('Payroll Services', 1),
 ('Bookkeepers', 1),
 ('Translation Services', 1),
 ('Floral Designers', 1),
 ('Kitchen Supplies', 1),
 ('Furniture Reupholstery', 1),
 ('Employment Agencies', 1),
 ('Hotel bar', 1),
 ('Septic Services', 1),
 ('Water Heater Installation/Repair', 1),
 ('Unofficial Yelp Events', 1),
 ('Cigar Bars', 1),
 ('Hostels', 1),
 ('Eyebrow Services', 1),
 ('Tai Chi', 1)]

In [20]:
newdt[:80]

                            0      1
0                 Restaurants  18413
1                        Food   9987
2                   Nightlife   2737
3                Coffee & Tea   2675
4                        Bars   2573
5                   Fast Food   2201
6                  Sandwiches   2056
7                     Mexican   1860
8      American (Traditional)   1819
9                       Pizza   1704
10         Breakfast & Brunch   1703
11             Specialty Food   1642
12                    Burgers   1516
13                    Italian   1379
14                    Chinese   1361
15             American (New)   1356
16                   Desserts   1239
17                   Bakeries   1189
18                      Cafes   1119
19                    Grocery   1063
20                   Japanese   1045
21  Event Planning & Services   1036
22                   Shopping    967
23  Ice Cream & Frozen Yogurt    862
24                    Seafood    825
25                 Sushi Bars    774
26               Asian Fusion    730
27     Juice Bars & Smoothies    721
28              Chicken Wings    709
29         Convenience Stores    700
..                        ...    ...
50              Cocktail Bars    367
51                Ethnic Food    366
52                    Lounges    364
53                 Vietnamese    357
54     Food Delivery Services    356
55                 Automotive    348
56                      Greek    327
57                Food Trucks    321
58             Health Markets    303
59                  Wine Bars    297
60                Gluten-Free    295
61                    Buffets    286
62                     French    284
63               Comfort Food    278
64                 Drugstores    243
65                   Hot Dogs    237
66                       Soup    235
67                  Caribbean    224
68                     Donuts    223
69             Latin American    217
70               Local Flavor    209
71                 Gastropubs    205
72                      Halal    204
73                    Tex-Mex    203
74            Hotels & Travel    203
75                 Bubble Tea    198
76         Tapas/Small Plates    193
77                   Hawaiian    193
78                  Tea Rooms    189
79                    Noodles    187

[80 rows x 2 columns]

In [21]:
feature.head(5)

        Feature       IDF
0     Nightlife  2.260651
1  Coffee & Tea  2.281199
2          Bars  2.316173
3     Fast Food  2.457968
4    Sandwiches  2.520462

In [22]:
for tag in range(feature.shape[0]):
    ft = feature.loc[tag,'Feature']
    idf = feature.loc[tag,'IDF']
    for i in range(data_business.shape[0]):
        each_line = data_business['category'][i].split(", ")
        if ft in each_line:
            data_business.loc[i,ft] = 1 / len(each_line) * idf
        else:
            data_business.loc[i,ft] = 0

In [23]:
data_business.to_csv('business.csv')

In [34]:
data_business = pd.read_csv('business.csv',index_col=0)

In [19]:
data_business.describe()

,latitude,longitude,stars,review_count,Coffee & Tea,Nightlife,Bars,Specialty Food,Sandwiches,Breakfast & Brunch,...,Halal,Gluten-Free,Food Delivery Services,Wine Bars,Delis,Health Markets,Tea Rooms,Sports Bars,Gastropubs,Tapas/Small Plates
count,10093.000000,10093.000000,10093.000000,10093.000000,10093.000000,10093.000000,10093.000000,10093.000000,10093.000000,10093.000000,...,10093.000000,10093.000000,10093.000000,10093.000000,10093.000000,10093.000000,10093.000000,10093.000000,10093.000000,10093.000000
mean,43.681057,-79.392436,3.464629,40.679976,0.085730,0.042937,0.041434,0.044661,0.046176,0.042146,...,0.014134,0.011574,0.012990,0.008203,0.012787,0.010787,0.013781,0.008029,0.011599,0.008941
std,0.046194,0.061268,0.761838,76.631472,0.243476,0.125094,0.123169,0.163826,0.184199,0.172326,...,0.121245,0.101253,0.120315,0.074128,0.121964,0.101473,0.129941,0.074040,0.121292,0.096226
min,43.592327,-79.703390,1.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,43.650806,-79.418194,3.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,43.664176,-79.393529,3.500000,15.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,43.696332,-79.371987,4.000000,43.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,43.876501,-79.137178,5.000000,2121.000000,1.062800,1.135335,0.770337,1.305053,1.364459,1.367786,...,2.111857,1.423607,2.149401,0.872972,2.190085,1.462638,2.197861,1.102882,2.205763,2.297511

In [20]:
data_business.head()

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,...,Halal,Gluten-Free,Food Delivery Services,Wine Bars,Delis,Health Markets,Tea Rooms,Sports Bars,Gastropubs,Tapas/Small Plates
0,C9oCPomVP0mtKa8z99E3gg,Bakery Gateau,"865 York Mills Road, Unit 1",Toronto,ON,M3B 1Y6,43.754093,-79.349548,4.5,8,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
1,NDuUMJfrWk52RA-H-OtrpA,Bolt Fresh Bar,1170 Queen Street W,Toronto,ON,M6J 1J5,43.642889,-79.425429,3.0,57,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
2,SP_YXIEwkFPPl_9anCYmpQ,The Steady Cafe & Bar,1051 Bloor Street W,Toronto,ON,M6H 1M4,43.660494,-79.432099,3.5,29,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
3,mlHC2XcU9Bows6cnYEmRgg,Mad Crush Wine Bar,582 College Street,Toronto,ON,M6G 1B3,43.655420,-79.413352,4.0,9,...,0.0,0.0,0.0,0.727477,0.0,0.0,0.0,0.0,0.0,0.0
4,RFbMVekR8lU9tPJ8sWrwHg,Tavolino,619 Mount Pleasant Road,Toronto,ON,M4S 2M5,43.704229,-79.388230,4.0,18,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0